spring:
  application:
    name: order-service
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
#启用hystrix
feign:
  hystrix:
    enabled: true
#暴露 hystrix.stream 监控端点
#暴露刷新端点
management:
  endpoints:
    web:
      exposure:
        include: refresh
#配置集群
---
spring:
  profiles: order1
server:
  port: 8201

---
spring:
  profiles: order2
server:
  port: 8202