sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
#暴露 hystrix.stream 监控端点
#暴露刷新端点
management:
  endpoints:
    web:
      exposure:
        include: refresh